In [1]:
import pandas as pd

## 맞춤법/띄어쓰기된 데이터 불러오기

In [2]:
df = pd.read_excel('data/py_hanspell.xlsx')

In [3]:
df

,name,review,rate,hanspell_review
0,월인당[한국관광 품질인증/Korea Quality],"지난 주말, 부모님과 함께 널찍한 노마루가 있는 산노을 방에서 묵었어요. 꽃피는 봄...",5.00,"지난 주말, 부모님과 함께 널찍한 노마루가 있는 산노을 방에서 묵었어요. 꽃피는 봄..."
1,와담정[한국관광 품질인증/Korea Quality],월정교와도 가깝고 방도 넘 깨끗했습니다. 사장님도 너무 친절하시고 좋았어요. 특히 ...,5.00,월정교와도 가깝고 방도 넘 깨끗했습니다. 사장님도 너무 친절하시고 좋았어요. 특히 ...
2,와담정[한국관광 품질인증/Korea Quality],목조 한옥이다보니 벌레가 너무 많았어요. 톡톡이라고 깨알보다 작은 벌레들이 이불에도...,2.65,목조 한옥이다보니 벌레가 너무 많았어요. 톡톡이라고 깨알보다 작은 벌레들이 이불에도...
3,비센트호텔[한국관광 품질인증/Korea Quality],"아주 늦은시간 도착했는데 프론트 친절하시고, 객실정비도 잘 되어있고 수건도 넉넉해...",5.00,"아주 늦은시간 도착했는데 프론트 친절하시고, 객실정비도 잘 되어있고 수건도 넉넉해..."
4,비센트호텔[한국관광 품질인증/Korea Quality],가격대비 만족합니다호텔도 깨끗한 편이에요,5.00,가격대비 만족합니다호텔도 깨끗한 편이에요
...,...,...,...,...
115139,공주한옥마을[한국관광 품질인증/Korea Quality],팀 워크숍을 준비하면서 어디가 적당할까하고 조사해본 결과 공주한옥마을을 선정했다. ...,5.00,팀 워크숍을 준비하면서 어디가 적당할까하고 조사해본 결과 공주한옥마을을 선정했다. ...
115140,공주한옥마을[한국관광 품질인증/Korea Quality],어머니와 함께 사곡관 (공동 욕실과 화장실을 쓰는 개별방) 에 1박 투숙하였습니다....,4.00,어머니와 함께 사곡관 (공동 욕실과 화장실을 쓰는 개별방) 에 1박 투숙하였습니다....
115141,공주한옥마을[한국관광 품질인증/Korea Quality],지난 5월 가족여행으로 1박2일 공주를 다녀왔습니다. 공주 '한옥마을 정안관'에 숙...,5.00,지난 5월 가족여행으로 1박2일 공주를 다녀왔습니다. 공주 '한옥마을 정안관'에 숙...
115142,공주한옥마을[한국관광 품질인증/Korea Quality],지은지 얼마 안된 건물처럼 깨끗한 한옥시설을 갖추었다. 화장실도 신식으로 되어 있고...,5.00,지은지 얼마 안된 건물처럼 깨끗한 한옥시설을 갖추었다. 화장실도 신식으로 되어 있고...
115143,공주한옥마을[한국관광 품질인증/Korea Quality],"Didnt는 정말로 머무른다, 단지 모양을보기 위해 갔다 - 보라. 별로 아무것도,...",3.00,"Didnt는 정말로 머무른다, 단지 모양을보기 위해 갔다 - 보라. 별로 아무것도,..."

## 긍부정 label

In [4]:
df_pos = df[df['rate']==5]
df_neg = df[df['rate']<2.5]

In [5]:
df_pos['is_pos']=1
df_neg['is_pos']=0

<ipython-input-5-dee9229358c5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pos['is_pos']=1
<ipython-input-5-dee9229358c5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neg['is_pos']=0

In [6]:
df_labeled = pd.concat([df_pos, df_neg])
df_labeled.reset_index(drop=True, inplace=True)

In [7]:
df_labeled.head()

,name,review,rate,hanspell_review,is_pos
0,월인당[한국관광 품질인증/Korea Quality],"지난 주말, 부모님과 함께 널찍한 노마루가 있는 산노을 방에서 묵었어요. 꽃피는 봄...",5.0,"지난 주말, 부모님과 함께 널찍한 노마루가 있는 산노을 방에서 묵었어요. 꽃피는 봄...",1
1,와담정[한국관광 품질인증/Korea Quality],월정교와도 가깝고 방도 넘 깨끗했습니다. 사장님도 너무 친절하시고 좋았어요. 특히 ...,5.0,월정교와도 가깝고 방도 넘 깨끗했습니다. 사장님도 너무 친절하시고 좋았어요. 특히 ...,1
2,비센트호텔[한국관광 품질인증/Korea Quality],"아주 늦은시간 도착했는데 프론트 친절하시고, 객실정비도 잘 되어있고 수건도 넉넉해...",5.0,"아주 늦은시간 도착했는데 프론트 친절하시고, 객실정비도 잘 되어있고 수건도 넉넉해...",1
3,비센트호텔[한국관광 품질인증/Korea Quality],가격대비 만족합니다호텔도 깨끗한 편이에요,5.0,가격대비 만족합니다호텔도 깨끗한 편이에요,1
4,비센트호텔[한국관광 품질인증/Korea Quality],깔끔하고 좋아요~^^,5.0,깔끔하고 좋아요~^^,1

In [8]:
labeled_result = pd.DataFrame()
labeled_result['review'] = df_labeled['hanspell_review']
labeled_result['is_pos'] = df_labeled['is_pos']

In [9]:
labeled_result

                                                  review  is_pos
0      지난 주말, 부모님과 함께 널찍한 노마루가 있는 산노을 방에서 묵었어요. 꽃피는 봄...       1
1      월정교와도 가깝고 방도 넘 깨끗했습니다. 사장님도 너무 친절하시고 좋았어요. 특히 ...       1
2      아주 늦은시간 도착했는데  프론트 친절하시고, 객실정비도 잘 되어있고 수건도 넉넉해...       1
3                                 가격대비 만족합니다호텔도 깨끗한 편이에요       1
4                                            깔끔하고 좋아요~^^       1
...                                                  ...     ...
84822  나는 여기에 예약을했고, 나는 거기를 빠져 나갔고, 방을 들여다 보았고, 더 나은 ...       0
84823  예약을 메일 응답을 느리고 혼란 예약을 (나는 내 이메일은 물론 모든 읽지 않았다)...       0
84824  아고 다에 예약 할 때 호텔은 2019 년 7 월까지만 리뷰합니다. agoda에 대...       0
84825  모기! ! ! ! 바다를 볼 가치가 없음 그리고 침대는 다른 사람들이 언급했듯이 정...       0
84826  여기에 적은 의견 중 1 개에서 언급했듯이, 위치는 정말 좋고 조용하며 경찰서 옆에...       0

[84827 rows x 2 columns]

## 부정 라벨 리뷰 추가 크롤링

In [10]:
extra_df = pd.read_csv('data/extra_neg_rev.csv', encoding='utf-8')

In [11]:
extra_neg = pd.DataFrame()
extra_neg['review'] = extra_df['review']
extra_neg['is_pos'] = 0

In [12]:
labeled_result = pd.concat([labeled_result, extra_neg])

In [18]:
labeled_result = labeled_result.dropna()

In [19]:
labeled_result

                                                 review  is_pos
0     지난 주말, 부모님과 함께 널찍한 노마루가 있는 산노을 방에서 묵었어요. 꽃피는 봄...       1
1     월정교와도 가깝고 방도 넘 깨끗했습니다. 사장님도 너무 친절하시고 좋았어요. 특히 ...       1
2     아주 늦은시간 도착했는데  프론트 친절하시고, 객실정비도 잘 되어있고 수건도 넉넉해...       1
3                                가격대비 만족합니다호텔도 깨끗한 편이에요       1
4                                           깔끔하고 좋아요~^^       1
...                                                 ...     ...
9808  차라리 옆에 휘슬락가세요 뷰 생각하고 일부러 슈페리어 잡았더니 방파제삼바리밖에안보이...       0
9809  호텔인척하는 모텔\n화장실들어가자마자 쉰내가 .. 욕조는 노랗게 때가 묻었고 사람머...       0
9810                        다른건 호텔 평균이고. 6층 객실 와이파이 안잡힘       0
9811  마지막날숙소로 잡았는데 제일 별로였어요 \n층간소음에 욕실에 하수구냄새인지 뭔지 계...       0
9812  대체적으로 만족합니다만 유리창이 너무 더러워서 오션뷰는 포기해야했습니다. 또한 수면...       0

[94638 rows x 2 columns]

## 데이터 저장하기

In [20]:
labeled_result.to_csv('data/PNlabeled_review.csv',index=False, encoding="utf-8")